### ISSUE TITLE
KITTI rank

### ISSUE THREAD

**Issue by xuwuzhou** [TurtleZhong/LVIO-SAM#3]
So , where is it ranked on KITTI?

**Comment by TurtleZhong** [comment]
Since the IMU params of KITTI is not accurate， and the frequency of KITTI IMU is low, So we have not submit results to KITTI. The KITTI datasets is just used for test

**Comment by xuwuzhou** [comment]
KITTI的rank排名应该是不允许使用IMU的，你们可以把IMU去掉跑KITII测试看看

**Comment by xuwuzhou** [comment]
顺便问一下，你们这个发布了相关了论文吗，arxiv也行

**Comment by TurtleZhong** [comment]
有的 但论文比较粗糙，已经录用了，发表了挂上来



---Original---
From: ***@***.***&gt;
Date: Tue, Jan 18, 2022 09:33 AM
To: ***@***.***&gt;;
Cc: "Xinliang ***@***.******@***.***&gt;;
Subject: Re: [TurtleZhong/LVIO-SAM] KITTI rank (Issue #3)




 
顺便问一下，你们这个发布了相关了论文吗，arxiv也行

**Comment by TurtleZhong** [comment]
暂时没法去掉imu这个方法，可能要改的多一些



---Original---
From: ***@***.***&gt;
Date: Tue, Jan 18, 2022 09:31 AM
To: ***@***.***&gt;;
Cc: "Xinliang ***@***.******@***.***&gt;;
Subject: Re: [TurtleZhong/LVIO-SAM] KITTI rank (Issue #3)




 
KITTI的rank排名应该是不允许使用IMU的，你们可以把IMU去掉跑KITII测试看看

**Comment by TurtleZhong** [comment]
> 顺便问一下，你们这个发布了相关了论文吗，arxiv也行


Hi, the paper is [here](https://github.com/TurtleZhong/LVIO-SAM/blob/master/Lidar%20Visual%20Inertial%20Odometry-final.pdf). Actually, I have the idea after the LIO-SAM project, and I write the code and then I was called to do other work.  After half a year,When I was halfway through writing my paper, I found that LVI-SAM appeared. So.... I just find a near conference and submit my paper.
