### ISSUE TITLE
Relate paper

### ISSUE THREAD

**Issue by chengwei0427** [TurtleZhong/LVIO-SAM#5]
Hi, @TurtleZhong 

Can you upload the relate paper? 

Thank you.

**Comment by TurtleZhong** [comment]
> Hi, @TurtleZhong
> 
> Can you upload the relate paper?
> 
> Thank you.


Hi, the paper is [here](https://github.com/TurtleZhong/LVIO-SAM/blob/master/Lidar%20Visual%20Inertial%20Odometry-final.pdf). Actually, I have the idea after the LIO-SAM project, and I write the code and then I was called to do other work.  After half a year,When I was halfway through writing my paper, I found that LVI-SAM appeared. So.... I just find a near conference and submit my paper.
